-- Garante tabelas antigas sejam removidas e um novo schema seja criado
DROP SCHEMA IF EXISTS DATA_WAREHOUSE CASCADE;

CREATE SCHEMA DATA_WAREHOUSE;

-- Cria dimensão TEMPO
DROP TABLE IF EXISTS DATA_WAREHOUSE.TEMPO;

CREATE TABLE DATA_WAREHOUSE.TEMPO 
(
CD_TEMPO SERIAL NOT NULL,
ANO CHAR (4) NOT NULL,
MES CHAR(2) NOT NULL);

ALTER TABLE DATA_WAREHOUSE.TEMPO ADD CONSTRAINT TEMPO_PK PRIMARY KEY (CD_TEMPO);

-- Cria dimensão CLIENTE
DROP TABLE IF EXISTS DATA_WAREHOUSE.CLIENTE;

CREATE TABLE DATA_WAREHOUSE.CLIENTE (

CD_CLIENTE INT NOT NULL,
NM_CLIENTE VARCHAR(30) NOT NULL
);

ALTER TABLE DATA_WAREHOUSE.CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (CD_CLIENTE);

-- Cria dimensão LOJA
DROP TABLE IF EXISTS DATA_WAREHOUSE.LOJA ;

CREATE TABLE DATA_WAREHOUSE.LOJA (

CD_LOJA INT NOT NULL,
NM_LOJA VARCHAR(30) NOT NULL);

ALTER TABLE DATA_WAREHOUSE.LOJA ADD CONSTRAINT LOJA_PK PRIMARY KEY (CD_LOJA);

-- Cria dimensão VENDEDOR
DROP TABLE IF EXISTS DATA_WAREHOUSE.VENDEDOR;

CREATE TABLE DATA_WAREHOUSE.VENDEDOR (

CD_VENDEDOR INT NULL,
NM_VENDEDOR VARCHAR (30) NOT NULL);

ALTER TABLE DATA_WAREHOUSE.VENDEDOR ADD CONSTRAINT VENDEDOR_PK PRIMARY KEY (CD_VENDEDOR);

-- Cria fato VENDA
DROP TABLE IF EXISTS DATA_WAREHOUSE.VENDA;

CREATE TABLE DATA_WAREHOUSE.VENDA (

CD_VENDA INT NOT NULL,
CD_TEMPO INT NOT NULL,
CD_LOJA INT NOT NULL,
CD_CLIENTE INT NOT NULL,
CD_VENDEDOR INT NOT NULL,
NR_PAR_PREVISTAS INT NOT NULL,
NR_PAR_ATRASADAS INT NOT NULL,
NR_PAR_PAGAS INT NOT NULL,
VLR_PAR_PREVISTAS NUMERIC NOT NULL);

ALTER TABLE DATA_WAREHOUSE.VENDA ADD CONSTRAINT VENDA_PK PRIMARY KEY (
    CD_VENDA,
    CD_TEMPO,
    CD_LOJA,
    CD_CLIENTE,
    CD_VENDEDOR);

ALTER TABLE DATA_WAREHOUSE.VENDA ADD CONSTRAINT VEN_TEMPO_FK FOREIGN KEY(CD_TEMPO)
        REFERENCES TEMPO(CD_TEMPO);
CREATE INDEX CD_TEMPO_I ON DATA_WAREHOUSE.VENDA(CD_TEMPO);

ALTER TABLE DATA_WAREHOUSE.VENDA ADD CONSTRAINT VEN_LOJA_FK FOREIGN KEY(CD_LOJA)
        REFERENCES DATA_WAREHOUSE.LOJA(CD_LOJA);
CREATE INDEX CD_LOJA_I ON DATA_WAREHOUSE.VENDA(CD_LOJA);

ALTER TABLE DATA_WAREHOUSE.VENDA ADD CONSTRAINT VEN_CLIENTE_FK FOREIGN KEY(CD_CLIENTE)
        REFERENCES DATA_WAREHOUSE.CLIENTE(CD_CLIENTE);
CREATE INDEX CD_CLIENTE_I ON DATA_WAREHOUSE.VENDA(CD_CLIENTE);

ALTER TABLE DATA_WAREHOUSE.VENDA ADD CONSTRAINT VEN_VENDEDOR_FK FOREIGN KEY(CD_VENDEDOR)
        REFERENCES DATA_WAREHOUSE.VENDEDOR(CD_VENDEDOR);
CREATE INDEX CD_VENDEDOR_I ON DATA_WAREHOUSE.VENDA(CD_VENDEDOR);